name: Deploy .NET API to Linux Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    env:
      DOTNET_INSTALL_DIR: /home/rdp/.dotnet
      DOTNET_ROOT: /home/rdp/.dotnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .NET install folder
        run: mkdir -p /home/rdp/.dotnet

      - name: Add .NET to PATH
        run: echo "/home/rdp/.dotnet" >> $GITHUB_PATH

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Check .NET
        run: |
          which dotnet
          dotnet --version
          dotnet --list-sdks

      - name: Find project file
        run: find . -name "*.csproj"

      - name: Restore dependencies
        run: dotnet restore ./StoreApi.csproj

      - name: Build
        run: dotnet build ./StoreApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./StoreApi.csproj --configuration Release --output ./publish --no-build

      - name: Show published files
        run: |
          ls -la ./publish
          find ./publish -name "*.dll"

      - name: Create deploy folder
        run: |
          mkdir -p /var/www/storeApi

      - name: Stop API service
        run: |
          sudo -n systemctl stop storeApi.service || true

      - name: Deploy files
        run: |
          rsync -a --delete ./publish/ /var/www/storeApi/

      - name: Show deployed files
        run: |
          ls -la /var/www/storeApi
          find /var/www/storeApi -name "*.dll"

      - name: Start API service
        run: |
          sudo -n systemctl start storeApi.service

      - name: Check API service
        run: |
          systemctl is-active storeApi.service