name: Deploy .NET API to Linux Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore ./StoreApi.csproj

      - name: Build
        run: dotnet build ./StoreApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./StoreApi.csproj --configuration Release --output ./publish --no-build

      - name: Copy files to server
        uses: easingthemes/ssh-deploy@v6.0.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SOURCE: "publish/"
          TARGET: "/var/www/myapi/"
          ARGS: "-rlgoDzvc --delete"

      - name: Restart API service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart myapi.service
            sudo systemctl status myapi.service --no-pager
